System/Mvc5/Controllers/AlumnoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain;
using Service;
using System.Net;
using Mvc5.Models;

namespace Mvc5.Controllers
{
    public class AlumnoController : Controller
    {
        private ApplicationDbContext _context = new ApplicationDbContext();
        private IAlumnoService _alumnoService;

        private IUbigeoService _ubigeoService;
        public AlumnoController()
        {
            if (_alumnoService==null)
            {
                _alumnoService = new AlumnoService();
            }
            if (_ubigeoService == null)
            {
                _ubigeoService = new UbigeoService();
            }
        }
        // GET: Alumno
        public ActionResult Index(string criterio)
        {
            var al = _alumnoService.GetAlumnos(criterio);
         

            
            return View(al);
        }

        // GET: Alumno/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var al = _alumnoService.GetAlumnooById(id);
            if (al == null)
            {
                return HttpNotFound();
            }
            return View(al);
        }

        public ActionResult Buscar(string criterio)
        {
            var ub= _ubigeoService.GetUbigeos(criterio);



            return View(ub);

        }

        // GET: Alumno/Create
        public ActionResult Create()
        {
            //Combo();
            return View();
        }

        //public List<SelectListItem> Departamentos()
        //{
        //    List<SelectListItem> DepartamentoId = new List<SelectListItem>();
        //    var dato = _ubigeoService.GetUbigeos().Where(u => u.IdUbigeo.Remove(0, 2).Equals("0000"));
        //    foreach (var item in dato)
        //    {
        //        DepartamentoId.Add(
        //            new SelectListItem()
        //            {
        //                Text = item.IdUbigeo,
        //                Value = item.Departamento
        //            });
        //    }
        //    return DepartamentoId;
        //}

        //public void Combo()
        //{


        //    var DepartamentoId = Departamentos();
        //    ViewBag.departamento = new SelectList(DepartamentoId, "Text", "Value");

        //    var ProvinciaId = new List<SelectListItem>() {
        //        new SelectListItem() { Text = "Seleccione", Value = "Seleccione" }
        //    };
        //    ViewBag.provincia = new SelectList(ProvinciaId, "Text", "Value");

        //    var DistritoId = new List<SelectListItem>() {
        //        new SelectListItem() { Text = "Seleccione", Value = "Seleccione" }
        //    };
        //    ViewBag.distrito = new SelectList(DistritoId, "Text", "Value");
        //}
        // POST: Alumno/Create
        [HttpPost]
        public ActionResult Create(Alumno alumno)
        {
            
            try
            {
                //Combo();
                // TODO: Add insert logic here
                if (ModelState.IsValid)
                {
                    _alumnoService.AddAlumno(alumno);

                    return RedirectToAction("Index");
                }
                return View("Create",alumno);
            }
            catch
            {
                return View();
            }
        }

        // GET: Alumno/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var al= _alumnoService.GetAlumnooById(id);

            if (al == null)
            {
                return HttpNotFound();
            }
            return View(al);
        }

        // POST: Alumno/Edit/5
        [HttpPost]
        public ActionResult Edit(Alumno alumno)
        {
            try
            {
                // TODO: Add update logic here

                if (ModelState.IsValid)
                {
                    _alumnoService.EditarAlumno(alumno);
                    
                    return RedirectToAction("Index");
                }
                return View(alumno);
            }
            catch
            {
                return View();
            }
        }

        // GET: Alumno/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var al = _alumnoService.GetAlumnooById(id);

            if (al == null)
            {
                return HttpNotFound();
            }
            return View(al);
        }

        // POST: Alumno/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                if (ModelState.IsValid)
                {
                    _alumnoService.EliminarAlumno(id);
                    

                    return RedirectToAction("Index");
                }
                return View(id);
            }
            catch
            {
                return View();
            }
        }
        //public JsonResult GetProvincias(int departmentId)
        //{

        //    string id = "";
        //    if (departmentId.ToString().Count() < 6 && departmentId.ToString().Any()) id = (0 + "" + departmentId);
        //    else id = departmentId.ToString();

        //    _context.Configuration.ProxyCreationEnabled = false;
        //    var provincias = _ubigeoService.GetUbigeos().Where(u => (u.IdUbigeo.ToString().Remove(0, 4).ToString() == "00") &&
        //                                            (u.IdUbigeo.ToString().Remove(2, 4).Equals(id.Remove(2, 4)))).
        //                                            OrderBy(u => u.Provincia);


        //    var provincia = new List<Ubigeo>();

        //    for (int i = 1; i < provincias.Count(); i++)
        //    {
        //        provincia.Add(provincias.ToList()[i]);
        //    }
        //    return Json(provincia);
        //}

        //public JsonResult GetDistritos(int provinciaId)
        //{

        //    string id = "";
        //    if (provinciaId.ToString().Count() < 6 && provinciaId.ToString().Count() > 0) id = (0 + "" + provinciaId);
        //    else { id = provinciaId.ToString(); }

        //    _context.Configuration.ProxyCreationEnabled = false;
        //    var Distritos = _ubigeoService.GetUbigeos().Where(p => p.IdUbigeo.ToString().Remove(0, 4) != "00" &&
        //                                                   p.IdUbigeo.ToString().Remove(4, 2).Equals(id.Remove(4, 2)));

        //    var distrito = new List<Ubigeo>();

        //    for (int i = 0; i < Distritos.Count(); i++)
        //    {
        //        distrito.Add(Distritos.ToList()[i]);
        //    }
        //    return Json(distrito);

        //}

    }
}

System/Mvc5/Views/Alumno/BuscarAlumno.cshtml

@{
    ViewBag.Title = "BuscarAlumno";
}

<h2>BuscarAlumno</h2>

<div class="form-horizontal">
    <div class="form-group">
        @Html.Label("Codigo")
        @Html.TextBox("codigo", "", new { @class = "form-control" })
        <button id="btnBuscar" type="button" class="btn btn-primary">Buscar</button>
    </div>
    <div class="form-group">
        @Html.Label("Descripción")
        @Html.TextBox("descripcion", "", new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.Label("Precio")
        @Html.TextBox("precio", "", new { @class = "form-control" })
    </div>
</div>

@section scripts{
    <script type="text/javascript">
        $(function () {
           $("#btnBuscar").on("click",function () {

               var codigo = $("#Dni").val();

               $.ajax({
                   method: "GET",
                   url: "/Producto/BuscarProductoByCodigo?codigo="+codigo
               }).done(function( result ) {
                   if (result.success === true) {
                       alert("El Producto existe..!!");
                       $("#descripcion").val(result.data.Nombres);
                       $("#precio").val(result.data.Apellidos);
                   }
                   else
                   {
                     alert("El Producto no existe..!!");
                   }
               });
           });
        });
    </script>
}

System/Mvc5/Views/Alumno/Create.cshtml
@model Domain.Alumno

@{
ViewBag.Title = "Create";
}
<center>
    <br />
    <br />
    <FONT FACE="impact" SIZE=2 COLOR="White">
        <h1>REGISTRAR ALUMNO</h1>

    </FONT>

    <br />
</center>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombres, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombres, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Apellidos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellidos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellidos, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Dni, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Dni, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Dni, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.FechaNacimiento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaNacimiento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaNacimiento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Genero, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                Masculino @Html.RadioButtonFor(model => model.Genero, "Masculino", new { htmlAttributes = new { @class = "form-control" } })

                Femenino @Html.RadioButtonFor(model => model.Genero, " Femenino", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Genero, "", new { @class = "text-danger" })
            </div>

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Celular, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Celular, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Celular, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.IdUbigeo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdUbigeo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdUbigeo, "", new { @class = "text-danger" })
              

            </div>
        </div>

    









            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                    @Html.ActionLink("Back to List", "Index", new { }, new { @class = "btn btn-success" })
                </div>
            </div>


        </div>
}



System/Mvc5/Views/Alumno/Delete.cshtml
@model Domain.Alumno

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Alumno</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellidos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellidos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Dni)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dni)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaNacimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genero)
        </dd>

       

        <dt>
            @Html.DisplayNameFor(model => model.Celular)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Celular)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ubigeo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ubigeo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

System/Mvc5/Views/Alumno/Details.cshtml
@model Domain.Alumno

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Alumno</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellidos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellidos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Dni)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dni)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaNacimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genero)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Celular)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Celular)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ubigeo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ubigeo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.AlumnoId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

System/Mvc5/Views/Alumno/Edit.cshtml
@model Domain.Alumno

@{
    ViewBag.Title = "Edit";
}

@*<h2>Edit</h2>*@


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Editar Alumno</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.AlumnoId)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombres, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombres, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellidos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellidos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellidos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Dni, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Dni, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Dni, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaNacimiento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaNacimiento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaNacimiento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Genero, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                Masculino @Html.RadioButtonFor(model => model.Genero, "Masculino", new { htmlAttributes = new { @class = "form-control" } })

                Femenino @Html.RadioButtonFor(model => model.Genero, " Femenino", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Genero, "", new { @class = "text-danger" })
            </div>

        </div>

    

        <div class="form-group">
            @Html.LabelFor(model => model.Celular, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Celular, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Celular, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdUbigeo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdUbigeo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdUbigeo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @*<a href="#" class="btn btn-info">Info</a>*@
                <input type="submit" value="Save" class="btn btn-info"> 
                @Html.ActionLink("Back to List", "Index", new { }, new{@class = "btn btn-warning"})
            </div>
        </div>
    </div>
}

<div>
   
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

System/Mvc5/Views/Alumno/Index.cshtml
@model IEnumerable<Domain.Alumno>

@{
    ViewBag.Title = "Index";
    //Layout = null;
}
<center>
    <br />
    <br />
    <FONT FACE="impact" SIZE=2 COLOR="White">
        <h1>REGISTRO DE ALUMNOS</h1>
        
    </FONT>
  
    <br />
</center>



@using (Html.BeginForm("Index","Alumno",FormMethod.Get))
{     
    <div class="form-inline">

        @Html.Label("Criterio :")
        @Html.TextBox("criterio","",new { @class="form-control"})
        <button type="submit" class="btn btn-danger">Buscar</button>
       @Html.ActionLink("Create New", "Create",new { }, new { @class = "btn btn-success" })
    </div>
    <br />
}
    

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombres)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Apellidos)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Dni)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </th>
       
        <th>
            @Html.DisplayNameFor(model => model.Genero)
        </th>
       
        <th>
            @Html.DisplayNameFor(model => model.Celular)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Direccion)
        </th>
      
        <th></th>
    </tr>

@foreach (var item in Model) {
   
    <tr >
        <td>
            @Html.DisplayFor(modelItem => item.Nombres)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Apellidos)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Dni)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaNacimiento)
        </td>
     
        <td >
            @Html.DisplayFor(modelItem => item.Genero)
        </td>
        
        <td>
            @Html.DisplayFor(modelItem => item.Celular)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Direccion)
        </td>
     
        <td>
            @*@Html.ActionLink("Edit", "Edit", new { id=item.AlumnoId }) |
            @Html.ActionLink("Details", "Details", new { id=item.AlumnoId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.AlumnoId })*@
            <a href="@Url.Action("Edit", new { id = item.AlumnoId })" title="Edit"
               style="margin-right: 3px;"
               class="btn btn-warning btn-sm">
                <i class="glyphicon glyphicon-pencil"></i>
                <span class="sr-only">Edit</span>
            </a>
            <a href="@Url.Action("Details", new { id = item.AlumnoId })" title="Details"
               style="margin-right: 3px;"
               class="btn btn-primary btn-sm">
                <i class="glyphicon glyphicon-list-alt"></i>
                <span class="sr-only">Details</span>
            </a>
            <a href="@Url.Action("Delete", new { id = item.AlumnoId })" title="Delete"
               style="margin-right: 3px;"
               class="btn btn-danger btn-sm">
                <i class="glyphicon glyphicon-trash"></i>
                <span class="sr-only">Delete</span>
            </a>
        </td>

        
    </tr>
}

</table>