System/Mvc5/Controllers/ApoderadoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain;
using Service;
using System.Net;

namespace Mvc5.Controllers
{
    public class ApoderadoController : Controller
    {

        private IApoderadoService _apoderadoService;
        private IUbigeoService _ubigeoService;
        public ApoderadoController()
        {
            if (_apoderadoService==null )
            {
                _apoderadoService = new ApoderadosService();

            }
            if (_ubigeoService==null)
            {
                _ubigeoService = new UbigeoService();
            }
        }
        // GET: Apoderado
        public ActionResult Index(string criterio)
        {
            var ap = _apoderadoService.GetApoderados(criterio);
            var ub = _ubigeoService.GetUbigeos();
            ViewBag.ubigeo = new SelectList(ub, "UbigeoId", "Codigo", " Departamento ", "Provincia", "Distrito", "PaisId");
            
            return View(ap);
        }

        // GET: Apoderado/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var ap = _apoderadoService.GetApoderadoById(id);
            if (ap == null)
            {
                return HttpNotFound();
            }
            return View(ap);
        }

        // GET: Apoderado/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Apoderado/Create
        [HttpPost]
        public ActionResult Create(Apoderado apoderado)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _apoderadoService.AddApoderado(apoderado);


                    return RedirectToAction("Index");
                }
                return View(apoderado);
            }
            catch
            {
                return View();
            }
        }

        // GET: Apoderado/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var ap = _apoderadoService.GetApoderadoById(id);
           
            if (ap == null)
            {
                return HttpNotFound();
            }
            return View(ap);
            
        }

        // POST: Apoderado/Edit/5
        [HttpPost]
        public ActionResult Edit(Apoderado apoderado)
        {
            try
            {
                // TODO: Add update logic here
                if (ModelState.IsValid)
                {
                    _apoderadoService.EditarApoderado(apoderado);
                    return RedirectToAction("Index");
                }
                return View(apoderado);
            }
            catch
            {
                return View();
            }
        }

        // GET: Apoderado/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var ap = _apoderadoService.GetApoderadoById(id);

            if (ap == null)
            {
                return HttpNotFound();
            }
            return View(ap);

           
        }

        // POST: Apoderado/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                if (ModelState.IsValid)
                {
                    _apoderadoService.EliminarApoderado(id);

                    return RedirectToAction("Index");
                }
                return View(id);
            }
            catch
            {
                return View();
            }
        }
        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
               
        //    }
        //    base.Dispose(disposing);
        //}

    }
}

System/Mvc5/Views/Apoderado/Create.cshtml
@model Domain.Apoderado

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Apoderado</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombres, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombres, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellidos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellidos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellidos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Dni, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Dni, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Dni, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.masculino, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.masculino)
                    @Html.ValidationMessageFor(model => model.masculino, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Femenino, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Femenino)
                    @Html.ValidationMessageFor(model => model.Femenino, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Celular, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Celular, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Celular, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UbigeoId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UbigeoId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UbigeoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

System/Mvc5/Views/Apoderado/Delete.cshtml
@model Domain.Apoderado

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Apoderado</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellidos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellidos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Dni)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dni)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.masculino)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.masculino)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Femenino)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Femenino)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Celular)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Celular)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UbigeoId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UbigeoId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

System/Mvc5/Views/Apoderado/Details.cshtml
@model Domain.Apoderado

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Apoderado</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellidos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellidos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Dni)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dni)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.masculino)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.masculino)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Femenino)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Femenino)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Celular)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Celular)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UbigeoId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UbigeoId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ApoderadoId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

System/Mvc5/Views/Apoderado/Edit.cshtml
@model Domain.Apoderado

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Apoderado</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ApoderadoId)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombres, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombres, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellidos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellidos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellidos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Dni, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Dni, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Dni, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.masculino, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.masculino)
                    @Html.ValidationMessageFor(model => model.masculino, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Femenino, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Femenino)
                    @Html.ValidationMessageFor(model => model.Femenino, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Celular, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Celular, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Celular, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UbigeoId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UbigeoId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UbigeoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

System/Mvc5/Views/Apoderado/Index.cshtml
@model IEnumerable<Domain.Apoderado>

@{
    ViewBag.Title = "Index";
}

<h2>Indexxx</h2>


   

@using (Html.BeginForm("Index","Apoderado", FormMethod.Get)) { 
<div class="form-inline">
    @Html.Label("Criterio :")
    @Html.TextBox("criterio","",new { @class="form-control"})
    <button type="submit" class="btn btn-danger">Buscar</button>
    @Html.ActionLink("Create New", "Create", new { } ,new { @class = "btn btn-success" })
</div>
    <br />
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombres)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Apellidos)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Dni)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.masculino)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Femenino)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Celular)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Direccion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UbigeoId)
        </th>

        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombres)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Apellidos)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Dni)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.masculino)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Femenino)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Celular)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Direccion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UbigeoId)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ApoderadoId }) |
            @Html.ActionLink("Details", "Details", new { id=item.ApoderadoId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ApoderadoId })
        </td>
    </tr>
}

</table>