System/Mvc5/Controllers/GradosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain;
using Service;
using System.Net;

namespace Mvc5.Controllers
{
    public class GradosController : Controller
    {
        // GET: Grados
        private INivelService _nivelService;
        private IGradoService _gradoService;
        public GradosController()
        {
            if (_nivelService==null)
            {
                _nivelService = new NivelService();

            }
            if (_gradoService==null)
            {
                _gradoService = new GradoService();
            }
            
        }
        public ActionResult Index(string criterio, Int32? nivel)
        {
            var gr = _gradoService.GetGrado(criterio,nivel);
            var ni = _nivelService.GetNiveles();
            ViewBag.nivel = new SelectList(ni, "NivelId", "Nombre");
            return View(gr);
        }

        // GET: Grados/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var gr = _gradoService.GetGradoById(id);
            if (gr == null)
            {
                return HttpNotFound();
            }
            return View(gr);
        }

        // GET: Grados/Create
        public ActionResult Create()
        {
            var ni = _nivelService.GetNiveles();
            ViewBag.nivel = new SelectList(ni, "NivelId", "Nombre");
            return View();
        }

        // POST: Grados/Create
        [HttpPost]
        public ActionResult Create(Grado grado)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _gradoService.AddGrado(grado);
                    
                    return RedirectToAction("Index");
                }
                return View(grado);
            }
            catch
            {
                return View();
            }
        }

        // GET: Grados/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var gr = _gradoService.GetGradoById(id);
            var ni = _nivelService.GetNiveles();
            ViewBag.nivel = new SelectList(ni, "NivelId", "Nombre");
            if (gr == null)
            {
                return HttpNotFound();
            }
            return View(gr);
        }

        // POST: Grados/Edit/5
        [HttpPost]
        public ActionResult Edit(Grado grado)
        {
            try
            {
                // TODO: Add update logic here

                if (ModelState.IsValid)
                {
                    _gradoService.EditarGrado(grado);
                    
                    return RedirectToAction("Index");
                }
                return View(grado);
            }
            catch
            {
                return View();
            }
        }

        // GET: Grados/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var gr = _gradoService.GetGradoById(id);
            
            if (gr == null)
            {
                return HttpNotFound();
            }
            return View(gr);
        }

        // POST: Grados/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                if (ModelState.IsValid)
                {
                    _gradoService.EliminarGrado(id);
                    

                    return RedirectToAction("Index");
                }
                return View(id);
            }
            catch
            {
                return View();
            }
        }
    }
}

System/Mvc5/Views/Grados/Create.cshtml
@model Domain.Grado

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Grado</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NivelId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NivelId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NivelId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

System/Mvc5/Views/Grados/Delete.cshtml
@model Domain.Grado

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Grado</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NivelId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NivelId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

System/Mvc5/Views/Grados/Details.cshtml
@model Domain.Grado

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Grado</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NivelId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NivelId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.GradoId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

System/Mvc5/Views/Grados/Edit.cshtml
@model Domain.Grado

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Grado</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.GradoId)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NivelId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NivelId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NivelId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

System/Mvc5/Views/Grados/Index.cshtml
@model IEnumerable<Domain.Grado>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
   
</p>

@using (Html.BeginForm("Index", "Grados", FormMethod.Get))
{

    <div class="form-inline">
        @*<div class="form-group">*@
        @Html.Label("Criterio:")
        @Html.TextBox("criterio", "", new { @class = "form-control" })

        @Html.Label("  Nivel :")
        @Html.DropDownList("nivel", ViewBag.nivel as SelectList, "[-- Seleccione --]", new { @class = "form-control" })
        @*</div>*@
        <button type="submit" class="btn btn-danger">Buscar</button>
        @Html.ActionLink("Create New", "Create", new { }, new { @class = "btn btn-success" })
    </div>
    <br />
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GradoId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NivelId)
        </th>
       
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GradoId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NivelId)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.GradoId }) |
            @Html.ActionLink("Details", "Details", new { id=item.GradoId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.GradoId })
        </td>
    </tr>
}

</table>